require "language/node"

class Ticketfairy < Formula
  desc "Command-line interface for the Ticket Fairy platform"
  homepage "https://www.ticketfairy.com/"
  # npm is the canonical distribution artifact for both npm and Homebrew.
  # Its tarballs are immutable post-publish, so
  # the URL + sha256 pair below is a stable pointer to the exact
  # bytes that shipped as v<version>. Regenerated by
  # `scripts/update-formula.sh` on every stable CLI release.
  url "https://registry.npmjs.org/ticketfairy/-/ticketfairy-0.1.2.tgz"
  version "0.1.2"
  sha256 "6cb9e1126ccd0c51a046cb1c6b8540817a99d4b6603ffa10dad787083db90dd0"
  license "MIT"

  depends_on "node"

  def install
    # `std_npm_args` resolves to the
    # canonical "install a node CLI into Homebrew's libexec sandbox"
    # incantation: it runs `npm install -g --prefix #{libexec}` with
    # the right flags (no scripts that would break in the sandbox,
    # production deps only, no audit). The CLI tarball pulled by
    # `url` above is the post-publish artifact (compiled `dist/`, no
    # devDeps), so we can install it directly.
    system "npm", "install", *std_npm_args
    # The published package installs as
    # `#{libexec}/lib/node_modules/ticketfairy/bin/run.js`
    # with `ticketfairy` as the package.json `bin` entry — Homebrew
    # surfaces it by symlinking from `bin/`.
    bin.install_symlink Dir[libexec/"bin/*"]
  end

  test do
    # Smoke test: `ticketfairy --version` prints the package name + version.
    assert_match "ticketfairy/", shell_output("#{bin}/ticketfairy --version")
  end
end
