require "language/node"

class Ticketfairy < Formula
  desc "Command-line interface for the Ticket Fairy platform"
  homepage "https://github.com/theticketfairy/ticketfairy-cli"
  # npm is the canonical distribution artifact for both npm and Homebrew.
  # Its tarballs are immutable post-publish, so
  # the URL + sha256 pair below is a stable pointer to the exact
  # bytes that shipped as v<version>. Regenerated by
  # `scripts/update-formula.sh` on every tag push from the CLI repo.
  url "https://registry.npmjs.org/@theticketfairy/cli/-/cli-0.1.0.tgz"
  version "0.1.0"
  sha256 "758e4f3a254178a77c86f46017996d4e39a8cade0ee6214c64aa3da7c16d0436"
  license "MIT"

  depends_on "node"

  def install
    # `std_npm_args` resolves to the
    # canonical "install a node CLI into Homebrew's libexec sandbox"
    # incantation: it runs `npm install -g --prefix #{libexec}` with
    # the right flags (no scripts that would break in the sandbox,
    # production deps only, no audit). The CLI tarball pulled by
    # `url` above is the post-publish artifact (compiled `dist/`, no
    # devDeps), so we can install it directly.
    system "npm", "install", *std_npm_args
    # The published package installs as
    # `#{libexec}/lib/node_modules/@theticketfairy/cli/bin/run.js`
    # with `ticketfairy` as the package.json `bin` entry — Homebrew
    # surfaces it by symlinking from `bin/`.
    bin.install_symlink Dir[libexec/"bin/*"]
  end

  test do
    # Smoke test: `ticketfairy --version` prints the package name +
    # version. The published package name is `@theticketfairy/cli`,
    # not `ticketfairy`, so we assert on a substring that's stable
    # across releases.
    assert_match "@theticketfairy/cli", shell_output("#{bin}/ticketfairy --version")
  end
end
